// ── RECIPE VAULT — DEMO DATA ─────────────────────────────────────────────────
// In the real app this data is built by scanning your cloud Drive PDFs.
// For Phase 1 we ship rich demo data so every feature is immediately usable.

const DEMO_RECIPES = [
  {
    id: 'r1',
    name: 'Cacio e Pepe',
    cuisine: 'Italian',
    emoji: '🍝',
    time: '20 min',
    servings: 2,
    cloudPath: '/Recipes/Italian/Cacio e Pepe.pdf',
    tags: ['Vegetarian', 'Quick'],
    description: 'Rome\'s simplest, most perfect pasta.',
    ingredients: [
      { amount: '200g', item: 'spaghetti or tonnarelli' },
      { amount: '100g', item: 'Pecorino Romano, finely grated' },
      { amount: '30g',  item: 'Parmigiano Reggiano, grated' },
      { amount: '2 tsp', item: 'coarsely ground black pepper' },
      { amount: '1 tsp', item: 'fine salt' },
    ],
    steps: [
      'Bring a large pot of well-salted water to a boil. Cook the pasta until 2 minutes before al dente, reserving 300ml of the starchy pasta water before draining.',
      'Toast the black pepper in a dry wide pan over medium heat for 30 seconds until fragrant. Add 120ml pasta water and let it simmer for 1 minute.',
      'Add the drained pasta to the pan and toss vigorously over medium-low heat, adding more pasta water a splash at a time to keep things saucy.',
      'Remove the pan from the heat. Wait 30 seconds, then add both cheeses in three additions, stirring constantly and adding pasta water as needed to create a silky, creamy sauce that coats every strand.',
      'Serve immediately in warm bowls with an extra crack of black pepper.',
    ],
    nutrition: { calories: 520, protein: 22, carbs: 74, fat: 16 },
  },
  {
    id: 'r2',
    name: 'Chicken Tikka Masala',
    cuisine: 'Indian',
    emoji: '🍛',
    time: '50 min',
    servings: 4,
    cloudPath: '/Recipes/Indian/Chicken Tikka Masala.pdf',
    tags: ['Gluten-free'],
    description: 'Creamy, spiced, deeply satisfying.',
    ingredients: [
      { amount: '700g',  item: 'boneless chicken thighs, cut into chunks' },
      { amount: '200ml', item: 'full-fat yoghurt' },
      { amount: '3 tbsp', item: 'tikka masala paste' },
      { amount: '2',    item: 'large onions, diced' },
      { amount: '400g', item: 'canned crushed tomatoes' },
      { amount: '200ml', item: 'heavy cream' },
      { amount: '2 tsp', item: 'garam masala' },
      { amount: '1 tsp', item: 'ground cumin' },
      { amount: '4 cloves', item: 'garlic, minced' },
      { amount: '1 inch', item: 'fresh ginger, grated' },
    ],
    steps: [
      'Marinate the chicken in yoghurt, 2 tbsp tikka paste, salt, and a squeeze of lime for at least 30 minutes (overnight is even better).',
      'Grill or broil the marinated chicken at high heat for 8–10 minutes, turning once, until lightly charred. Set aside.',
      'In a large pan, fry the onions in 2 tbsp oil until golden (about 10 min). Add garlic, ginger, and the remaining tikka paste and cook 2 minutes more.',
      'Pour in the crushed tomatoes and simmer for 10 minutes until the sauce darkens and thickens. Season with garam masala, cumin, salt.',
      'Stir in the cream and grilled chicken. Simmer gently for 5 minutes. Finish with a handful of fresh coriander and serve with basmati rice or naan.',
    ],
    nutrition: { calories: 610, protein: 48, carbs: 18, fat: 38 },
  },
  {
    id: 'r3',
    name: 'Street Tacos al Pastor',
    cuisine: 'Mexican',
    emoji: '🌮',
    time: '40 min',
    servings: 4,
    cloudPath: '/Recipes/Mexican/Tacos al Pastor.pdf',
    tags: ['Weekend'],
    description: 'Pineapple-marinated pork, corn tortillas, all the fixings.',
    ingredients: [
      { amount: '600g',  item: 'pork shoulder, thinly sliced' },
      { amount: '3 tbsp', item: 'adobo sauce (from chipotles in adobo)' },
      { amount: '2 tsp', item: 'dried oregano' },
      { amount: '1 tsp', item: 'ground cumin' },
      { amount: '1',    item: 'chipotle pepper, minced' },
      { amount: '120ml', item: 'pineapple juice' },
      { amount: '8',    item: 'small corn tortillas' },
      { amount: '150g', item: 'fresh pineapple, diced' },
      { amount: '1',    item: 'white onion, finely diced' },
      { amount: '1 bunch', item: 'fresh coriander, chopped' },
    ],
    steps: [
      'Mix together the adobo, chipotle, oregano, cumin, pineapple juice, salt, and pepper. Coat the pork slices well and marinate for at least 20 minutes.',
      'Heat a cast-iron skillet or griddle over high heat. Cook the pork in batches for 2–3 minutes per side until caramelised and slightly crispy at the edges.',
      'Roughly chop the cooked pork into small pieces while still hot.',
      'Warm the corn tortillas directly over a gas flame or in a dry pan for 30 seconds each side.',
      'Build each taco: pork, a few cubes of fresh pineapple, white onion, coriander, and a squeeze of lime. Serve with salsa verde.',
    ],
    nutrition: { calories: 480, protein: 36, carbs: 42, fat: 18 },
  },
  {
    id: 'r4',
    name: 'Matcha Cheesecake',
    cuisine: 'Japanese',
    emoji: '🍰',
    time: '90 min + chill',
    servings: 8,
    cloudPath: '/Recipes/Japanese/Matcha Cheesecake.pdf',
    tags: ['Dessert', 'Baked'],
    description: 'Silky Japanese-style cheesecake with earthy matcha.',
    ingredients: [
      { amount: '500g', item: 'cream cheese, room temperature' },
      { amount: '3 tbsp', item: 'ceremonial-grade matcha powder' },
      { amount: '150g', item: 'caster sugar' },
      { amount: '3',   item: 'large eggs' },
      { amount: '200ml', item: 'heavy cream' },
      { amount: '2 tbsp', item: 'plain flour' },
      { amount: '1 tsp', item: 'vanilla extract' },
      { amount: '120g', item: 'digestive biscuits, crushed' },
      { amount: '60g',  item: 'unsalted butter, melted' },
    ],
    steps: [
      'Preheat oven to 160°C (fan 140°C). Mix crushed biscuits with melted butter and press firmly into the base of a lined 20cm springform tin. Chill for 15 minutes.',
      'Beat cream cheese and sugar together until completely smooth. Sift in the matcha and beat again until uniform and vivid green.',
      'Add the eggs one at a time, beating well after each. Stir in cream, vanilla, and flour until just combined — don\'t overwork it.',
      'Pour the filling over the chilled base. Place the tin in a deep roasting dish and fill with enough boiling water to come halfway up the tin.',
      'Bake for 55 minutes until the edges are set but the centre has a gentle wobble. Turn off the oven, leave the door ajar, and let the cheesecake cool inside for 1 hour. Chill for at least 4 hours before slicing.',
    ],
    nutrition: { calories: 440, protein: 9, carbs: 32, fat: 31 },
  },
  {
    id: 'r5',
    name: 'Vietnamese Pho Bo',
    cuisine: 'Vietnamese',
    emoji: '🍜',
    time: '3 hrs',
    servings: 6,
    cloudPath: '/Recipes/Vietnamese/Pho Bo.pdf',
    tags: ['Gluten-free', 'Weekend'],
    description: 'Long-simmered beef broth, rice noodles, fresh herbs.',
    ingredients: [
      { amount: '1.5kg', item: 'beef bones (marrow + knuckle)' },
      { amount: '500g',  item: 'beef brisket' },
      { amount: '400g',  item: 'flat rice noodles (bánh phở)' },
      { amount: '3',    item: 'star anise' },
      { amount: '1',    item: 'cinnamon stick' },
      { amount: '4 cloves', item: 'whole cloves' },
      { amount: '3 tbsp', item: 'fish sauce' },
      { amount: '1 tbsp', item: 'rock sugar' },
      { amount: '1',    item: 'large onion, halved and charred' },
      { amount: '50g',  item: 'fresh ginger, charred' },
    ],
    steps: [
      'Blanch bones in boiling water for 5 minutes. Drain and rinse well — this gives you a clear, clean broth.',
      'Char the onion and ginger halves directly over a gas flame until lightly blackened. This adds the characteristic smoky sweetness.',
      'Simmer bones, brisket, charred onion, and ginger in 3.5 litres water for 2.5 hours. Add spices (star anise, cinnamon, cloves) in the last 45 minutes.',
      'Remove brisket and slice thinly. Strain the broth through a fine sieve. Season with fish sauce, rock sugar, and salt.',
      'Soak then cook rice noodles per packet instructions. Divide into bowls with sliced brisket, ladle over boiling broth, and serve with bean sprouts, fresh basil, lime wedges, and hoisin sauce.',
    ],
    nutrition: { calories: 390, protein: 34, carbs: 38, fat: 10 },
  },
  {
    id: 'r6',
    name: 'Classic Margherita Pizza',
    cuisine: 'Italian',
    emoji: '🍕',
    time: '25 min + rise',
    servings: 2,
    cloudPath: '/Recipes/Italian/Margherita Pizza.pdf',
    tags: ['Vegetarian'],
    description: 'Neapolitan-style, blistered in a very hot oven.',
    ingredients: [
      { amount: '300g', item: 'strong bread flour' },
      { amount: '7g',  item: 'fast-action dried yeast' },
      { amount: '1 tsp', item: 'fine salt' },
      { amount: '1 tsp', item: 'caster sugar' },
      { amount: '200ml', item: 'warm water' },
      { amount: '200ml', item: 'passata' },
      { amount: '1 clove', item: 'garlic, grated' },
      { amount: '150g', item: 'fresh mozzarella' },
      { amount: '1 handful', item: 'fresh basil leaves' },
      { amount: '2 tbsp', item: 'good olive oil' },
    ],
    steps: [
      'Combine flour, yeast, salt, and sugar. Add warm water and mix to a shaggy dough. Knead for 8 minutes until smooth and elastic. Cover and rise for 1 hour.',
      'Preheat oven to its maximum temperature (ideally 280°C+) with a heavy baking tray or pizza stone inside.',
      'Mix passata with grated garlic, a pinch of salt, and 1 tbsp olive oil — no cooking needed.',
      'Divide dough into two balls. Stretch each ball by hand on a floured surface into thin rounds; don\'t use a rolling pin.',
      'Spoon sauce over the base, tear over the mozzarella, then slide onto the preheated stone or tray. Bake 7–9 minutes until the crust is blistered and the cheese is bubbling. Finish with fresh basil and a drizzle of olive oil.',
    ],
    nutrition: { calories: 560, protein: 24, carbs: 78, fat: 18 },
  },
];

// Cuisines derived from recipes
function getCuisines() {
  const source = (typeof state !== 'undefined' && state.recipes && state.recipes.length)
    ? state.recipes
    : DEMO_RECIPES;
  const seen = new Set();
  const list = [];
  source.forEach(r => {
    if (r.cuisine && !seen.has(r.cuisine)) { seen.add(r.cuisine); list.push(r.cuisine); }
  });
  return list.sort();
}
